Document confusing module test behavior
panorama-ed/memo_wise pull request #123
Opened 2021-03-09 19:02 UTC by JacobEvelyn

**Before merging:**

- [ ] If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)

2021-03-09 19:03 UTC, JacobEvelyn commented on README.md
> +### A Note on Testing
I couldn't figure out a good place in YARD to put this but let me know if there is!

2021-03-09 19:30 UTC, ms-ati commented on CHANGELOG.md
> +- Documentation of confusing module test behavior
Seems fine to me

2021-03-09 19:31 UTC, ms-ati approved these changes
LGTM!

2021-03-09 19:31 UTC, ms-ati approved these changes
LGTM!

2021-03-11 22:50 UTC, jemmaissroff requested changes

2021-03-11 22:50 UTC, jemmaissroff commented on README.md
> +like this between your tests:
Can we be more explicit and say in a `before_each` or `after_each` block?

2021-03-12 17:43 UTC, ms-ati approved these changes
LGTM

2021-03-12 17:46 UTC, jemmaissroff approved these changes

2021-03-12 18:11 UTC, merged